---
- name: Destroy the EC2 Server
# ==============================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": "ap-south-1"
      "2": "ap-northeast-2"
      "3": "ap-southeast-1"
      "4": "ap-southeast-2"
      "5": "ap-northeast-1"
      "6": "eu-central-1"
      "7": "eu-west-1"
      "8": "eu-west-2"
      "9": "sa-east-1"
      "10": "us-east-1"
      "11": "us-east-2"
      "12": "us-west-1"
      "13": "us-west-2"

  # These variable files are included so the ec2-security-group role
  # knows which ports to open

  vars_prompt:
    - name: "aws_region_var"
      prompt: |
        In what region is the server located?
          1. Asia Pacific   (Mumbai)
          2. Asia Pacific   (Seoul)
          3. Asia Pacific   (Singapore)
          4. Asia Pacific   (Sydney)
          5. Asia Pacific   (Tokyo)
          6. EU             (Frankfurt)
          7. EU             (Ireland)
          8. EU             (London)
          9. South America  (Sao Paulo)
          10. US East       (Northern Virginia)
          11. US East       (Ohio)
          12. US West       (Northern California)
          13. US West       (Oregon)
        Please choose the number of your region. Press enter for default (#3) region.
      default: "3"
      private: no

    - name: "aws_instance_name"
      prompt: "\nWhat is the instance name? Press enter for default (streisand).\n"
      default: "streisand"
      private: no

    - name: "aws_access_key"
      prompt: "\n\nThe following information can be found in the IAM Management Console.\nhttps://console.aws.amazon.com/iam/home?#security_credential\n\nWhat is your AWS Access Key ID?\n"
      private: no

    - name: "aws_secret_key"
      prompt: "\nWhat is your AWS Secret Access Key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now terminate your server and release the Elastic IP. Press Enter to begin destruction...\n"

  pre_tasks:
    - name: Set the AWS Region fact
      set_fact:
        aws_region: "{{ regions[aws_region_var] }}"


  roles:
    - destroy-amazon


- include: streisand.yml
